import React from "react";

export const SampleDataFoodEaten = [
  {
    food: "Taco",
    caloriesPerGram: 789,
    protein: 20,
    fat: 2,
    fiber: 5,
    carbs: 5,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Pizza",
    caloriesPerGram: 1032,
    protein: 10,
    fat: 12,
    fiber: 54,
    carbs: 25,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Burger",
    caloriesPerGram: 950,
    protein: 15,
    fat: 8,
    fiber: 3,
    carbs: 20,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Pasta",
    caloriesPerGram: 600,
    protein: 12,
    fat: 6,
    fiber: 2,
    carbs: 30,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Steak",
    caloriesPerGram: 1200,
    protein: 25,
    fat: 18,
    fiber: 1,
    carbs: 3,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Sushi",
    caloriesPerGram: 400,
    protein: 8,
    fat: 5,
    fiber: 2,
    carbs: 20,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Chicken Salad",
    caloriesPerGram: 550,
    protein: 10,
    fat: 4,
    fiber: 5,
    carbs: 15,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Lasagna",
    caloriesPerGram: 850,
    protein: 15,
    fat: 10,
    fiber: 4,
    carbs: 25,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Fish and Chips",
    caloriesPerGram: 1200,
    protein: 18,
    fat: 20,
    fiber: 2,
    carbs: 35,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Spaghetti",
    caloriesPerGram: 700,
    protein: 14,
    fat: 7,
    fiber: 3,
    carbs: 30,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Omelette",
    caloriesPerGram: 400,
    protein: 12,
    fat: 9,
    fiber: 1,
    carbs: 2,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Rice Bowl",
    caloriesPerGram: 850,
    protein: 10,
    fat: 5,
    fiber: 2,
    carbs: 40,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Caesar Salad",
    caloriesPerGram: 600,
    protein: 7,
    fat: 8,
    fiber: 4,
    carbs: 15,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Hot Dog",
    caloriesPerGram: 500,
    protein: 5,
    fat: 12,
    fiber: 1,
    carbs: 20,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Crispy Chicken",
    caloriesPerGram: 700,
    protein: 18,
    fat: 10,
    fiber: 3,
    carbs: 25,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Shrimp Scampi",
    caloriesPerGram: 600,
    protein: 10,
    fat: 6,
    fiber: 2,
    carbs: 20,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Vegetable Stir Fry",
    caloriesPerGram: 400,
    protein: 6,
    fat: 5,
    fiber: 8,
    carbs: 15,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Grilled Cheese Sandwich",
    caloriesPerGram: 700,
    protein: 8,
    fat: 15,
    fiber: 1,
    carbs: 20,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Ice Cream",
    caloriesPerGram: 300,
    protein: 3,
    fat: 10,
    fiber: 0,
    carbs: 30,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Chocolate Cake",
    caloriesPerGram: 500,
    protein: 5,
    fat: 20,
    fiber: 1,
    carbs: 40,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
  {
    food: "Fruit Salad",
    caloriesPerGram: 250,
    protein: 2,
    fat: 1,
    fiber: 10,
    carbs: 30,
    caloriesUnit: "kJ",
    proteinUnit: "gm",
    fatUnit: "gm",
    fiberUnit: "gm",
    carbsUnit: "gm",
  },
];

export default SampleDataFoodEaten;
